steps:

  - name: 'gcr.io/cloud-builders/go'
    args: ['install', './src/soma']
    env: ['PROJECT_ROOT=soma']

  - name: 'gcr.io/cloud-builders/go'
    args: ['test', 'soma']
    env: ['PROJECT_ROOT=soma']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']

images: ['gcr.io/$PROJECT_ID/soma']